### ISSUE TITLE
new branch for influxdb 0.9.0

### ISSUE THREAD

**Issue by n1tr0g** [influxdb/influxdb-ruby#86] opened 2015-05-30 04:11 UTC
Should you create a new branch for the upcoming influxDB 0.9.0 ? 

Would be good to start implementing the new features and API changes.

**Comment by chrishiestand** [comment] 2015-06-04 22:27
+1

**Comment by chrishiestand** [comment] 2015-06-04 22:30
duplicate of https://github.com/influxdb/influxdb-ruby/issues/77

**Comment by toddboom** [comment] 2015-07-06 16:35
@n1tr0g we're working on it. should be out later today!

**Closed by toddboom** 2015-07-06 16:35 UTC
